-- RBAC + PHI Masking Configuration

USE ROLE ACCOUNTADMIN;
USE DATABASE SNOREMD_DB;

-- Create Custom Roles (with governance intent)
CREATE ROLE IF NOT EXISTS DE_ROLE
    COMMENT = 'Full read/write access to RAW, STAGING, ANALYTICS';

CREATE ROLE IF NOT EXISTS ANALYST_ROLE
    COMMENT = 'Read-only on ANALYTICS; PHI masked';

CREATE ROLE IF NOT EXISTS CLINIC_ROLE
    COMMENT = 'Read-only on ANALYTICS; scoped to clinic_id';

-- Role hierarchy
GRANT ROLE DE_ROLE TO ROLE SYSADMIN;
GRANT ROLE ANALYST_ROLE TO ROLE DE_ROLE;
GRANT ROLE CLINIC_ROLE TO ROLE DE_ROLE;

-- Warehouse Access
GRANT USAGE ON WAREHOUSE SNOREMD_WH TO ROLE DE_ROLE;
GRANT USAGE ON WAREHOUSE SNOREMD_WH TO ROLE ANALYST_ROLE;
GRANT USAGE ON WAREHOUSE SNOREMD_WH TO ROLE CLINIC_ROLE;

-- Database & Schema Privileges
GRANT USAGE ON DATABASE SNOREMD_DB TO ROLE DE_ROLE;
GRANT USAGE ON DATABASE SNOREMD_DB TO ROLE ANALYST_ROLE;
GRANT USAGE ON DATABASE SNOREMD_DB TO ROLE CLINIC_ROLE;

-- DE_ROLE: full access to all layers
GRANT USAGE ON SCHEMA SNOREMD_DB.RAW TO ROLE DE_ROLE;
GRANT USAGE ON SCHEMA SNOREMD_DB.STAGING TO ROLE DE_ROLE;
GRANT USAGE ON SCHEMA SNOREMD_DB.ANALYTICS TO ROLE DE_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SNOREMD_DB.RAW TO ROLE DE_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SNOREMD_DB.STAGING TO ROLE DE_ROLE;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA SNOREMD_DB.ANALYTICS TO ROLE DE_ROLE;

-- Ensure future tables inherit privileges
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA SNOREMD_DB.RAW TO ROLE DE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA SNOREMD_DB.STAGING TO ROLE DE_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA SNOREMD_DB.ANALYTICS TO ROLE DE_ROLE;

-- ANALYST + CLINIC: read-only access to ANALYTICS layer only
GRANT USAGE ON SCHEMA SNOREMD_DB.ANALYTICS TO ROLE ANALYST_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOREMD_DB.ANALYTICS TO ROLE ANALYST_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOREMD_DB.ANALYTICS TO ROLE ANALYST_ROLE;

GRANT USAGE ON SCHEMA SNOREMD_DB.ANALYTICS TO ROLE CLINIC_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOREMD_DB.ANALYTICS TO ROLE CLINIC_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOREMD_DB.ANALYTICS TO ROLE CLINIC_ROLE;

-- PHI Dynamic Data Masking Policies
-- Only DE_ROLE, SYSADMIN, ACCOUNTADMIN see raw values
-- All other roles receive masked output

USE SCHEMA SNOREMD_DB.ANALYTICS;

CREATE OR REPLACE MASKING POLICY phi_string_mask
    AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('DE_ROLE', 'ACCOUNTADMIN', 'SYSADMIN') THEN val
        ELSE '****MASKED****'
    END
    COMMENT = 'Masks PHI string fields for non-DE roles';

CREATE OR REPLACE MASKING POLICY phi_date_mask
    AS (val DATE) RETURNS DATE ->
    CASE
        WHEN CURRENT_ROLE() IN ('DE_ROLE', 'ACCOUNTADMIN', 'SYSADMIN') THEN val
        ELSE NULL
    END
    COMMENT = 'Masks PHI date_of_birth for non-DE roles';

-- Apply masking policies to PHI columns
ALTER TABLE SNOREMD_DB.ANALYTICS.DIM_PATIENTS
    MODIFY COLUMN email_hash SET MASKING POLICY phi_string_mask;

ALTER TABLE SNOREMD_DB.ANALYTICS.DIM_PATIENTS
    MODIFY COLUMN phone_hash SET MASKING POLICY phi_string_mask;

ALTER TABLE SNOREMD_DB.ANALYTICS.DIM_PATIENTS
    MODIFY COLUMN date_of_birth SET MASKING POLICY phi_date_mask;

SELECT 'RBAC and masking policies applied successfully.' AS status;